[project]
name = "07-secure-data-encryption-system-using-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.2",
    "streamlit>=1.44.1",
]
